---
# tasks file for htpc-nas

# NFS Version 3 Server Installation and Configuration
- block:

  - name: Install NFS Server
    apt: name=nfs-kernel-server state=installed update_cache=yes cache_valid_time=3600

  - name: Configure NFS shares in /etc/exports
    lineinfile: dest=/etc/exports regexp='^{{ htpc_media_path }}' line='{{ htpc_media_path }} *(rw,insecure,all_squash,anonuid={{ htpc_user_uid }},anongid={{ htpc_user_gid }})'
    when: htpc_nas_nfs
    notify:
      - update nfs exports

  - name: Make sure NFS server is started on boot
    service: name=nfs-kernel-server state=started enabled=yes

  when: htpc_nas_nfs
  tags:
    - nfs

# SAMBA ( Windows File Sharing ) Installation and Configuration
- block:

  - name: Install SAMBA server
    apt: name=samba state=installed update_cache=yes cache_valid_time=3600

  - name: Update SAMBA configuration
    template: src=smb.conf dest=/etc/samba/smb.conf owner=root group=root
    notify:
      - create samba users
      - restart samba

  - name: Make sure SAMBA server is started on boot
    service: name=samba state=started enabled=yes

  when: htpc_nas_cifs
  tags:
    - cifs

# Netatalk ( Mac File Sharing ) Installation and Configuration
- block:

  - name: Add Netatalk Ubuntu Repository
    apt_repository: repo=ppa:igoritl/netatalk state=present update_cache=yes

  - name: Install Netatalk
    apt: name=netatalk state=present

  - name: Update Netatalk Config
    template: src=afp.conf.j2 dest=/etc/netatalk/afp.conf owner=root group=root mode=0644 backup=yes
    notify:
      - restart netatalk

  - name: Enable Netatalk in /etc/default/netatalk
    template: src=default_netatalk.j2 dest=/etc/default/netatalk owner=root group=root mode=644
    notify:
      - restart netatalk

  - name: Update Avahi Config
    template: src=afpd.service.j2 dest=/etc/avahi/services/afpd.service owner=root group=root mode=0644 backup=yes
    notify:
      - restart avahi

  - name: Enable Netatalk Service
    service: name=netatalk state=started enabled=yes

  - name: Enable Avahi Service
    service: name=avahi-daemon state=started enabled=yes

  when: htpc_nas_afp
  tags:
    - afp