---
# handlers file for htpc-nas

- name: update nfs exports
  command: /usr/sbin/exportfs -a

- name: create samba users
  shell: (echo "{{ htpc_user_password }}"; echo "{{ htpc_user_password }}") | smbpasswd -s -a {{ htpc_user_username }}

- name: restart samba
  service: name={{ item }} state=restarted
  with_items:
    - nmbd
    - smbd

- name: restart netatalk
  service: name=netatalk state=restarted

- name: restart avahi
  service: name=avahi-daemon state=restarted
